# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Flag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Detail', :path => './Frameworks/Detail/'
  pod 'Core', :path => './Frameworks/Core/'
  pod 'Home', :path => './Frameworks/Home/'
  # Pods for Flag

end
